### ISSUE TITLE
Overlapping word cloud

### ISSUE THREAD

**Issue by Meruja** [IjzerenHein/react-tag-cloud#2]
I have used your library to produce word cloud. When I use rotation function to rotate words I got overlapping. How to resolve it? Do I need to modify the CSS file?
![img5](https://user-images.githubusercontent.com/28688743/35720313-14b96a0e-0813-11e8-9f8b-2df221debc6a.png)

**Comment by IjzerenHein** [comment]
Can you provide me with a link to the code?

**Comment by Meruja** [comment]
yeah... sure..
[WordCloud.jsx.tar.gz](https://github.com/IjzerenHein/react-tag-cloud/files/1697778/WordCloud.jsx.tar.gz)

**Comment by Meruja** [comment]
I have fixed that. It's my fault. Shall I close the issue? But one thing I need to clarify. If you are using d3-cloud as backbone then it should produce the wordCloud as below.  But why  you could not support to random rotation?
![d3cloud](https://user-images.githubusercontent.com/28688743/35956228-53d7182a-0cba-11e8-8cf9-39608e5a1f91.png)

**Comment by IjzerenHein** [comment]
What do you mean, I don't understand your last question. You can still do that, you can pass in a Function to the `rotate` prop.

**Comment by Meruja** [comment]
What I try to say is, when we use rotate=Math.random() function, the wordcloud should look like the above image. But when I use tag-cloud library, for rotate=Math.random() it horizontally displays words. Random means it should display words in different angle. Am I? I don't understand what do you mean by "can pass in a Function to the rotate prop."?

**Comment by IjzerenHein** [comment]
@Meruja Could you paste a code snippet here on how you are using it?

**Comment by Meruja** [comment]
<TagCloud
                            className='tag-cloud'
                            style={{
                                fontFamily: 'sans-serif',
                                //fontSize: () => Math.round(Math.random() * 50) + 16,
                                fontSize: 30,
                                color: () => randomColor({
                                    hue: 'blue'
                                }),
                                padding: 5,
                            }}>
                            {
                                this.state.wordList.map((e,key) => {
                                    if (e.text.length>5){
                                        return <div rotate={Math.random() * 1} style={{fontSize: Math.random()* e.text.length}}>{e.text}</div>
                                    }
                                    else
                                    {
                                        return <div rotate={Math.random() * 90} style={{fontSize: Math.random()* e.text.length}}>{e.text}</div>
                                    }

                                })
                            }
                        </TagCloud>

**Comment by IjzerenHein** [comment]
https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet

**Comment by IjzerenHein** [comment]
You're not using using `rotate` in your example.

**Comment by Meruja** [comment]
sorry for the mistake

 <TagCloud
                            className='tag-cloud'
                            style={{
                                fontFamily: 'sans-serif',
                                fontSize: () => Math.round(Math.random()*30),
                                color: () => randomColor(),
                                padding: 12,
                            }}>
                            {
                                this.state.wordList.map((e) => {
                                    if (e.text.length>8){
                                        return <div rotate={Math.random()} style={{padding:e.text.length+1}}>{e.text}</div>
                                    }
                                    else
                                    {
                                        return <div rotate={90}>{e.text}</div>
                                    }
                                })
                            }
                        </TagCloud>

**Comment by IjzerenHein** [comment]
Hi, ah I see now. I've taken a closer look at the issues and found a couple problems. I've published a new version (v1.1.2), which fixes the bulk of the placement issues. In some cases I still see very small overlapping issues though, but it should be a lot better. Cheers 


PS, you can use the triple backtick technique to paste in code fragments, making it easier for everyone to read. No need to paste in images that way ;)
https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#code
