### ISSUE TITLE
Possible to prevent words from being cut from the cloud?

### ISSUE THREAD

**Issue by KosGrillis** [IjzerenHein/react-tag-cloud#7]
I've noticed that if a word/phrase in the cloud is either too long or has too large a font for the word cloud container, it is not displayed. Is there a way to prevent this?

**Comment by IjzerenHein** [comment]
Hi Kos. Not sure how to prevent this. The layouting is handled by the underlying d3-cloud component so I have very little control over it. What you could do is to make the size of the component larger and clip the excess content with `overflow: hidden`
