### ISSUE TITLE
Warning: Can't call setState (or forceUpdate) on an unmounted component. This is a no-op, but it indicates a memory leak in your application

### ISSUE THREAD

**Issue by riccardogenova** [IjzerenHein/react-tag-cloud#8]
Warning: Can't call setState (or forceUpdate) on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in the componentWillUnmount method.

On componentWillUnmount maybe you should unmount setState calling ?

![screen shot 2018-06-22 at 14 47 54](https://user-images.githubusercontent.com/17598688/41777421-8ddbd472-762b-11e8-907f-da28ca7bfe06.png)

**Comment by IjzerenHein** [comment]
Hi, thanks for letting me know. I've just published an update for this on NPM, v1.1.3 👍

**Comment by IjzerenHein** [comment]
Hi, can I close this?
